---
- name: Rotate secret_id
  hosts: localhost
  become: true
  tasks:
  - name: Generate a secret-id for the given approle
    community.hashi_vault.vault_write:
      url: "{{ vault_addr }}"
      path: auth/approle/role/aap2_controller/secret-id
      auth_method: approle
      role_id: "{{ role_id }}"
      secret_id: "{{ secret_id }}"
    register: new_secret_id
  
  - name: Display the role ID and secret ID
    ansible.builtin.debug:
      msg:
        - "secret-id: {{ new_secret_id.data.data.secret_id }}"
