---
- name: Rotate secret_id
  hosts: localhost
  become: true
  tasks:
  - name: Generate a secret-id for the given approle
    community.hashi_vault.vault_write:
      url: "{{ vault_addr }}"
      path: auth/approle/role/aap2_controller/secret-id
      auth_method: approle
      role_id: "{{ role_id }}"
      secret_id: "{{ secret_id }}"
    register: new_secret_id
  
  - name: Display the role ID and secret ID
    ansible.builtin.debug:
      msg:
        - "secret-id: {{ new_secret_id.data.data.secret_id }}"
      
  - name: update the secret ID
    awx.awx.credential:
      controller_host: 10.0.1.4
      controller_password: password
      controller_username: admin
      validate_certs: false
      name: vault_trust_approle
      credential_type: HashiCorp Vault Secret Lookup
      organization: Default
      inputs:
        url: 'http://10.0.1.5:8200'
        role_id: ceaabd5a-1c79-6c0d-0901-4b33c1071101
        secret_id: "{{ new_secret_id.data.data.secret_id }}"
       
  
 # rIwa9qRRJ6cNS59td0LsWjQc5IoeCypuHtoJAZBj
 # BzImEwwTZlByrY73341WehgxHXijKJCUByet8cwjXMWX8ooGiMmHVU0VuIO8Htu9lYKhLmb1iPPNfzHAqk0Yxojv8nCIWUhYHc981mDPtS3doeR55WRJocw5d8eC60To
      
