---
- name: Prove we can do stuff as root
  hosts: all
  become: true
  tasks:
  - name: Touch a file in the root homedir
    command: touch /root/this_was_made_using_approle.{{ ansible_date_time.epoch }}
    
